spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  datasource:
    url: jdbc:h2:file:./data/db;MODE=PostgreSQL;AUTO_SERVER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  graphql:
    graphiql:
      enabled: true
  h2:
    console:
      enabled: true
      path: /h2-console
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
